title: Fitness Motivation
author: Abby Henrikson
email: apeskind999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We have all needed some kind of motivation a long the way. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
